version: '3.1'

services: 

  localstack:
    image: localstack/localstack:latest
    environment: 
      - AWS_DEFAULT_REGION=eu-central-1
      - EDGE_PORT=4566
      - SERVICES=lambda,s3
    ports: 
      - '4566-4583:4566-4583'
    volumes: 
      - "${TEMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    image: mongo
    hostname: mongodb
    restart: always
    container_name: mongodb
    ports:
      - 27017:27017
    networks:
      - mongo-network
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo -u root -p example) -eq 1
      interval: 10s
      start_period: 30s
    
    entrypoint:
        - bash
        - -c
        - |
            touch /data/replica.key
            echo  "123456" >> /data/replica.key
            chmod 400 /data/replica.key
            chown 999:999 /data/replica.key
            exec docker-entrypoint.sh $$@     
    command: "mongod --bind_ip_all --replSet replicaSet01 --keyFile /data/replica.key"
networks:
  mongo-network:
    driver: bridge
