const e = require("@feathersjs/errors");
const PAPEO_ERRORS = {
  PHONENUMBER_NOT_VALID: {
    code: 101,
    type: e.BadRequest,
    en: "Your phone number has an incorrect format. Please enter your phone number without country code.",
    de: "Deine Telefonnummer hat ein falsches Format. Bitte gib deine Telefonnummer ohne Ländervorwahl ein.",
    es: "Su número de teléfono tiene un formato incorrecto. Por favor, introduzca su número de teléfono sin el código de país.",
    fr: "Votre numéro de téléphone a un format incorrect. Veuillez saisir votre numéro de téléphone sans l'indicatif du pays.",
    it: "Il tuo numero di telefono ha un formato errato. Inserisci il tuo numero di telefono senza il codice del paese.",
  },
  VERIFICATION_CODE_NOT_VALID: {
    code: 102,
    type: e.BadRequest,
    en: "Verification code is not valid",
    de: "Verifikationscode ist nicht gültig",
    es: "El código de verificación no es válido",
    fr: "Le code de vérification n'est pas valide",
    it: "Il codice di verifica non è valido",
  },
  USER_WITH_PHONENUMBER_ALREADY_EXISTS: {
    code: 103,
    type: e.BadRequest,
    en: "An user with this phone number already exists",
    de: "Ein Nutzer mit dieser Telefonummer existiert bereits",
    es: "Ya existe un usuario con este número de teléfono",
    fr: "Un utilisateur avec ce numéro de téléphone existe déjà",
    it: "Esiste già un utente con questo numero di telefono",
  },
  USERNAME_ALREADY_EXISTS: {
    code: 104,
    type: e.BadRequest,
    en: "An user with this username already exists",
    de: "Ein Nutzer mit diesem Nutzernamen existiert bereits",
    es: "Ya existe un usuario con este nombre de usuario",
    fr: "Un utilisateur avec ce nom d'utilisateur existe déjà",
    it: "Esiste già un utente con questo nome utente",
  },
  EMAIL_ALREADY_EXISTS: {
    code: 105,
    type: e.BadRequest,
    en: "An user with this email already exists",
    de: "Ein Nutzer mit dieser E-Mail existiert bereits",
    es: "Ya existe un usuario con este correo electrónico",
    fr: "Un utilisateur avec cette adresse e-mail existe déjà",
    it: "Esiste già un utente con questa email",
  },
  USERS_AGE_UNDER_16: {
    code: 106,
    type: e.BadRequest,
    en: "You have to be older than 16 years to use this app",
    de: "Um diese App zu benutzen, musst du mindestens 16 Jahre alt sein",
    es: "Para utilizar esta aplicación, debes tener al menos 16 años.",
    fr: "Pour utiliser cette application, vous devez avoir au moins 16 ans.",
    it: "Per utilizzare questa applicazione, devi avere almeno 16 anni.",
  },
  NOT_AUTHENTICATED: {
    code: 107,
    type: e.NotAuthenticated,
    en: "You are not logged in",
    de: "Du bist nicht eingeloggt",
    es: "No está conectado",
    fr: "Vous n'êtes pas connecté",
    it: "Non sei loggato",
  },
  USER_IS_BLOCKED: {
    code: 108,
    type: e.Forbidden,
    en: "Your account is blocked",
    de: "Dein Benutzerkonto ist gesperrt",
    es: "Su cuenta de usuario está bloqueada",
    fr: "Votre compte d'utilisateur est verrouillé",
    it: "Il tuo account utente è bloccato",
  },
  EMAIL_CANNOT_BE_CHANGED: {
    code: 109,
    type: e.Forbidden,
    en: "Your email address cannot be changed",
    de: "Deine E-Mail Adresse kann nicht geändert werden",
    es: "Su dirección de correo electrónico no puede ser modificada",
    fr: "Votre adresse électronique ne peut pas être modifiée",
    it: "Il tuo indirizzo email non può essere cambiato",
  },
  EMAIL_VERIFICATION_CODE_NOT_VALID: {
    code: 110,
    type: e.BadRequest,
    en: "Verification code is not valid",
    de: "Verifikationscode ist nicht gültig",
    es: "El código de verificación no es válido",
    fr: "Le code de vérification n'est pas valide",
    it: "Il codice di verifica non è valido",
  },
  REGISTERED_WITH_DIFFERENT_AUTHPLATFORM: {
    code: 111,
    type: e.Forbidden,
    en: "You've already signed up with another provider like Apple or Google.",
    de: "Sie haben sich bereits bei einem anderen Anbieter wie Apple oder Google angemeldet.",
    es: "Ya te has registrado con otro proveedor como Apple o Google.",
    fr: "vous vous êtes déjà inscrit auprès d'un autre fournisseur comme Apple ou Google",
    it: "Ti sei già registrato con un altro fornitore come Apple o Google.",
  },
  WRONG_USER_ROLE: {
    code: 112,
    type: e.Forbidden,
    en: "Not enough permissions",
    de: "Nicht genügend Berechtigungen",
    es: "No hay suficientes permisos",
    fr: "Pas assez de permissions",
    it: "Non abbastanza permessi",
  },
  PARTY_DOES_NOT_EXIST: {
    code: 201,
    type: e.NotFound,
    en: "Party not found",
    de: "Party existiert nicht",
    es: "El partido no existe",
    fr: "Le parti n'existe pas",
    it: "Il partito non esiste",
  },
  GUESTLIST_IS_FULL: {
    code: 113,
    type: e.BadRequest,
    en: "Guestlist is already full",
    de: "Die Gästeliste ist bereits voll",
    es: "La lista de invitados ya está completa",
    fr: "La liste des invités est déjà complète",
    it: "La lista degli invitati è già piena",
  },
  USER_IS_ALREADY_GUEST: {
    code: 114,
    type: e.BadRequest,
    en: "You are already a guest",
    de: "Du bist bereits in der Gästeliste",
    es: "Ya estás en la lista de invitados",
    fr: "Vous êtes déjà sur la liste des invités",
    it: "Sei già sulla lista degli invitati",
  },
  TYPE_DOES_NOT_EXIST: {
    code: 115,
    type: e.NotFound,
    en: "Type does not exist",
    de: "Dieser Typ existiert nicht",
    es: "Este tipo no existe",
    fr: "Ce type n'existe pas",
    it: "Questo tipo non esiste",
  },
  PARTY_ALREADY_BOOKMARKED: {
    code: 116,
    type: e.BadRequest,
    en: "You already bookmarked this party",
    de: "Diese Party hast du bereits in deinen Favoriten gespeichert",
    es: "Ya has guardado esta fiesta en tus favoritos",
    fr: "Vous avez déjà enregistré cette fête dans vos favoris.",
    it: "Hai già salvato questa festa nei tuoi preferiti",
  },
  ENTITY_ALREADY_SWIPED: {
    code: 117,
    type: e.BadRequest,
    en: "You already swiped this User/Party",
    de: "Du hast diese/n Benutzer/in oder diese Party bereits geswiped",
    es: "Ya ha barrido a este usuario o partido",
    fr: "Vous avez déjà swipé cet utilisateur ou ce parti",
    it: "Hai già fatto un colpo di spugna su questo utente o partito",
  },
  YOU_CANNOT_FOLLOW_YOURSELF: {
    code: 118,
    type: e.BadRequest,
    en: "You cannot follow yourself",
    de: "Du kannst dir nicht selbst folgen",
    es: "No puedes seguirte a ti mismo",
    fr: "Vous ne pouvez pas vous suivre vous-même",
    it: "Non puoi seguire te stesso",
  },
  YOU_CANNOT_FRIEND_REQUEST_YOURSELF: {
    code: 119,
    type: e.BadRequest,
    en: "You cannot send yourself a friend request",
    de: "Du kannst dir nicht selbst eine Freundschaftsanfrage schicken",
    es: "No puedes enviarte a ti mismo una solicitud de amistad",
    fr: "Vous ne pouvez pas vous envoyer une demande d'ami",
    it: "Non puoi inviarti una richiesta di amicizia",
  },
  ALREADY_FRIENDS: {
    code: 120,
    type: e.BadRequest,
    en: "You are already friends",
    de: "Ihr seid bereits Freunde",
    es: "Ya sois amigos",
    fr: "Vous êtes déjà amis",
    it: "Siete già amici",
  },
  THERE_IS_NO_SUCH_FRIEND_REQUEST: {
    code: 121,
    type: e.BadRequest,
    en: "There is no friend request",
    de: "Diese Freundschaftsanfrage existiert nicht",
    es: "Esta solicitud de amistad no existe",
    fr: "Cette demande d'ami n'existe pas",
    it: "Questa richiesta di amicizia non esiste",
  },
  ALREADY_FOLLOWING_THIS_USER: {
    code: 122,
    type: e.BadRequest,
    en: "You are already following this user",
    de: "Du folgst diesem Nutzer bereits",
    es: "Ya estás siguiendo a este usuario",
    fr: "Vous suivez déjà cet utilisateur",
    it: "Stai già seguendo questo utente",
  },
  YOU_ARE_NOT_FOLLOWING_THIS_USER: {
    code: 123,
    type: e.BadRequest,
    en: "You are not following this user",
    de: "Du folgst diesem Nutzer nicht",
    es: "No estás siguiendo a este usuario",
    fr: "Vous ne suivez pas cet utilisateur",
    it: "Non stai seguendo questo utente",
  },
  LOCATION_MUST_BE_SET_FOR_FEED: {
    code: 124,
    type: e.BadRequest,
    en: "You must set your current location/ home location to use the feed",
    de: "Du musst deinen jetzigen Standort oder deinen Heimatstandort angeben um den Feed zu benutzen",
    es: "Debes introducir tu ubicación actual o la de tu casa para utilizar el feed.",
    fr: "Vous devez saisir votre position actuelle ou votre position à domicile pour utiliser le flux.",
    it: "Devi inserire la tua posizione attuale o la tua posizione di casa per utilizzare il feed.",
  },
  BOOKMARK_ALREADY_DELETED: {
    code: 125,
    type: e.BadRequest,
    en: "You already deleted this bookmark",
    de: "Du hast dieses Lesezeichen bereits gelöscht",
    es: "Ya has borrado este marcador",
    fr: "Vous avez déjà supprimé ce signet",
    it: "Hai già cancellato questo segnalibro",
  },
  PARTY_ALREADY_RATED: {
    code: 126,
    type: e.BadRequest,
    en: "You already rated this party",
    de: "Diese Party hast du bereits bewertet",
    es: "Ya has valorado esta fiesta",
    fr: "Vous avez déjà évalué cette fête",
    it: "Hai già valutato questa festa",
  },
  YOU_CANNOT_RATE_YOUR_OWN_PARTY: {
    code: 127,
    type: e.BadRequest,
    en: "You cannot rate your own party",
    de: "Du kannst deine eigene Party nicht bewerten",
    es: "No puedes calificar a tu propio partido",
    fr: "Vous ne pouvez pas évaluer votre propre parti",
    it: "Non puoi valutare il tuo stesso partito",
  },
  YOU_ARE_NOT_A_GUEST_OF_THIS_PARTY: {
    code: 128,
    type: e.BadRequest,
    en: "You are not a guest of this party",
    de: "Du kein Gast dieser Party",
    es: "No eres un invitado a esta fiesta",
    fr: "Vous n'êtes pas un invité à cette fête",
    it: "Non sei un ospite di questa festa",
  },
  POST_DOES_NOT_EXIST: {
    code: 129,
    type: e.NotFound,
    en: "Post not found",
    de: "Post existiert nicht",
    es: "El correo no existe",
    fr: "Le courrier n'existe pas",
    it: "La posta non esiste",
  },
  REPORT_DOES_NOT_EXIST: {
    code: 130,
    type: e.NotFound,
    en: "Report not found",
    de: "Report existiert nicht",
    es: "El informe no existe",
    fr: "Le rapport n'existe pas",
    it: "Il rapporto non esiste",
  },
  USER_ALREADY_REPORTED: {
    code: 131,
    type: e.BadRequest,
    en: "You already reported this user",
    de: "Du hast diesen Nutzer bereits gemeldet",
    es: "Ya has denunciado a este usuario",
    fr: "Vous avez déjà signalé cet utilisateur",
    it: "Hai già segnalato questo utente",
  },
  PARTY_ALREADY_REPORTED: {
    code: 132,
    type: e.BadRequest,
    en: "You already reported this party",
    de: "Du hast diese Party bereits gemeldet",
    es: "Ya ha registrado este partido",
    fr: "Vous avez déjà enregistré cette fête",
    it: "Hai già registrato questo partito",
  },
  USER_DOES_NOT_EXIST: {
    code: 133,
    type: e.BadRequest,
    en: "This user does not exist",
    de: "Dieser Nutzer existiert nicht",
    es: "Este usuario no existe",
    fr: "Cet utilisateur n'existe pas",
    it: "Questo utente non esiste",
  },
  YOU_ARE_NOT_THE_OWNER_OF_THIS_PARTY: {
    code: 134,
    type: e.Forbidden,
    en: "You are not the owner of this party",
    de: "Du bist nicht der Ersteller dieser Party",
    es: "Usted no es el creador de esta fiesta",
    fr: "Vous n'êtes pas le créateur de cette fête",
    it: "Non sei il creatore di questa festa",
  },
  YOU_MUST_BE_A_GUEST_TO_INVITE_OTHERS: {
    code: 135,
    type: e.BadRequest,
    en: "You must be a guest of the party to invite other users",
    de: "Du kannst keine Benutzer einladen, wenn du nicht Gast dieser Party bist",
    es: "No puedes invitar a los usuarios si no eres un invitado de esta fiesta.",
    fr: "Vous ne pouvez pas inviter des utilisateurs si vous n'êtes pas un invité de cette fête.",
    it: "Non puoi invitare utenti se non sei un ospite di questa festa.",
  },
  USER_ALREADY_INVITED: {
    code: 136,
    type: e.BadRequest,
    en: "You already invited this user to this party",
    de: "Du hast diesen Benutzer bereits zu dieser Party eingeladen",
    es: "Ya has invitado a este usuario a esta fiesta",
    fr: "Vous avez déjà invité cet utilisateur à cette fête",
    it: "Hai già invitato questo utente a questa festa",
  },
  YOU_CANNOT_INVITE_YOURSELF_TO_A_PARTY: {
    code: 137,
    type: e.BadRequest,
    en: "You cannot invite yourself to a party",
    de: "Du kannst Dich nicht selbst zu einer Party eingeladen",
    es: "No puedes invitarte a ti mismo a una fiesta",
    fr: "Vous ne pouvez pas vous inviter à une fête",
    it: "Non puoi invitarti a una festa",
  },
  USER_IS_ALREADY_ADMIN_OF_THIS_PARTY: {
    code: 138,
    type: e.BadRequest,
    en: "This user is already an admin of this party",
    de: "Dieser Benutzer ist bereits Admin dieser Party",
    es: "Este usuario ya es administrador de esta fiesta",
    fr: "Cet utilisateur est déjà administrateur de cette fête",
    it: "Questo utente è già amministratore di questo partito",
  },
  ONLY_PARTY_OWNERS_CAN_ADD_ADMINS: {
    code: 139,
    type: e.BadRequest,
    en: "Only the owner of a party can add party admins",
    de: "Nur der Ersteller einer Party kann Party-Admins hinzufügen",
    es: "Sólo el creador de un partido puede añadir administradores de partido",
    fr: "Seul le créateur d'une fête peut ajouter des administrateurs de la fête.",
    it: "Solo il creatore di un partito può aggiungere amministratori del partito",
  },
  ONLY_PARTY_OWNERS_CAN_REMOVE_ADMINS: {
    code: 140,
    type: e.BadRequest,
    en: "Only the owner of a party can remove party admins",
    de: "Nur der Ersteller einer Party kann Party-Admins entfernen",
    es: "Sólo el creador de un partido puede eliminar a los administradores del partido",
    fr: "Seul le créateur d'une fête peut supprimer les administrateurs de la fête.",
    it: "Solo il creatore di un partito può rimuovere gli amministratori del partito",
  },
  ONLY_USER_ON_THE_GUESTLIST_CAN_BE_ADMINS: {
    code: 141,
    type: e.BadRequest,
    en: "Only users on the guestlist can be party admins",
    de: "Nur Nutzer auf der Gästeliste können Party-Admins sein",
    es: "Sólo los usuarios de la lista de invitados pueden ser administradores de la fiesta",
    fr: "Seuls les utilisateurs figurant sur la liste des invités peuvent être administrateurs de la fête.",
    it: "Solo gli utenti della lista degli invitati possono essere amministratori del partito",
  },
  THIS_USER_IS_NOT_A_PARTY_ADMIN: {
    code: 142,
    type: e.BadRequest,
    en: "This user is not a party admin",
    de: "Dieser Nutzer ist kein Party-Admin",
    es: "Este usuario no es un administrador del partido",
    fr: "Cet utilisateur n'est pas un administrateur de la partie",
    it: "Questo utente non è un amministratore del partito",
  },
  UPLOAD_NOT_FINISHED: {
    code: 143,
    type: e.NotFound,
    en: "This file is not available yet",
    de: "Diese Datei ist noch nicht verfügbar",
    es: "Este archivo aún no está disponible",
    fr: "Ce fichier n'est pas encore disponible",
    it: "Questo file non è ancora disponibile",
  },
  YOU_ARE_NOT_PART_OF_THIS_CONVERSATION: {
    code: 144,
    type: e.Forbidden,
    en: "You are not part of this conversation",
    de: "Du bist nicht in diesem Chat",
    es: "No estás en este chat",
    fr: "Vous n'êtes pas dans ce chat",
    it: "Non sei in questa chat",
  },
  POST_ALREADY_REPORTED: {
    code: 145,
    type: e.BadRequest,
    en: "You already reported this post",
    de: "Du hast diesen Post bereits gemeldet",
    es: "Ya ha denunciado este puesto",
    fr: "Vous avez déjà signalé ce message",
    it: "Hai già segnalato questo post",
  },
  USER_IS_NOT_IN_YOUR_FRIEND_LIST: {
    code: 146,
    type: e.BadRequest,
    en: "This user is not in your friend list",
    de: "Dieser Nutzer ist nicht in deiner Freundesliste",
    es: "Este usuario no está en tu lista de amigos",
    fr: "Cet utilisateur n'est pas dans votre liste d'amis",
    it: "Questo utente non è nella tua lista di amici",
  },
  YOU_ALREADY_MENTIONED_THIS_USER: {
    code: 147,
    type: e.BadRequest,
    en: "You already mentioned this user",
    de: "Du hast diesen Nutzer bereits markiert",
    es: "Ya has etiquetado a este usuario",
    fr: "Vous avez déjà étiqueté cet utilisateur",
    it: "Hai già taggato questo utente",
  },
  MENTION_DOES_NOT_EXIST: {
    code: 148,
    type: e.BadRequest,
    en: "This mention does not exist",
    de: "Diese Markierung existiert nicht",
    es: "Esta marca no existe",
    fr: "Cette marque n'existe pas",
    it: "Questo marchio non esiste",
  },
  MENTION_UPLOAD_HAS_NO_POST: {
    code: 149,
    type: e.BadRequest,
    en: "You can only mention a user in posts",
    de: "Du kannst nur Nutzer in einem Post markieren",
    es: "Sólo se puede etiquetar a los usuarios en una publicación",
    fr: "Vous ne pouvez marquer que les utilisateurs dans un message",
    it: "Puoi solo taggare gli utenti in un post",
  },
  YOU_ALREADY_VOTED_FOR_THIS_USER: {
    code: 150,
    type: e.BadRequest,
    en: "You already voted for this user",
    de: "Du hast deine Stimme für diesen Nutzer bereits abgegeben",
    es: "Ya has votado por este usuario",
    fr: "Vous avez déjà voté pour cet utilisateur",
    it: "Hai già espresso il tuo voto per questo utente",
  },
  USER_IS_ALREADY_VERIFIED: {
    code: 151,
    type: e.BadRequest,
    en: "This user is already verified",
    de: "Dieser Nutzer ist bereits verifiziert",
    es: "Este usuario ya está verificado",
    fr: "Cet utilisateur est déjà vérifié",
    it: "Questo utente è già verificato",
  },
  USER_IS_HAS_NO_VERIFICATION_VIDEO: {
    code: 152,
    type: e.BadRequest,
    en: "This user has no verification video",
    de: "Dieser Nutzer hat kein Verifizierungsvideo",
    es: "Este usuario no tiene un vídeo de verificación",
    fr: "Cet utilisateur n'a pas de vidéo de vérification",
    it: "Questo utente non ha un video di verifica",
  },
  YOU_CANNOT_VOTE_FOR_YOURSELF: {
    code: 153,
    type: e.BadRequest,
    en: "You cannot vote for yourself",
    de: "Du kannst nicht selber für dich abstimmen",
    es: "No puedes votar por ti mismo",
    fr: "Vous ne pouvez pas voter pour vous-même",
    it: "Non puoi votare per te stesso",
  },
  YOU_MUST_BE_A_PARTY_KING_MEMBER_TO_MARK_YOURSELF_AS_AN_ARTIST: {
    code: 154,
    type: e.BadRequest,
    en: "You must have a party king membership to mark yourself as an artist",
    de: "Du kannst dich nur als Künstler eintragen, wenn du eine Party King Midgliedschaft hast",
    es: "Sólo puedes inscribirte como artista si eres miembro de Party King Mid.",
    fr: "Vous ne pouvez vous inscrire en tant qu'artiste que si vous êtes membre de Party King Mid.",
    it: "Puoi iscriverti come artista solo se hai un'iscrizione a Party King Mid.",
  },
  NOT_FOUND: {
    code: 155,
    type: e.NotFound,
    en: "Not found",
    de: "Nicht verfügbar",
    es: "No disponible",
    fr: "Non disponible",
    it: "Non disponibile",
  },
  YOU_DONT_HAVE_ENOUGH_PP_TO_PUBLISH_PARTY: {
    code: 156,
    type: e.BadRequest,
    en: "You do not have enough party points to publish a party",
    de: "Du hast nicht genügend Party-Points um eine Party zu veröffentlichen",
    es: "No tienes suficientes Puntos de Fiesta para publicar una fiesta.",
    fr: "Vous n'avez pas assez de points de fête pour publier une fête.",
    it: "Non hai abbastanza punti festa per pubblicare una festa.",
  },
  NOT_CLOSE_ENOUGH_TO_PARTY: {
    code: 157,
    type: e.BadRequest,
    en: "Your location is not at the party",
    de: "Dein Standort ist nicht auf der Party",
    es: "Su ubicación no está en la fiesta",
    fr: "Votre emplacement n'est pas à la fête",
    it: "La tua posizione non è alla festa",
  },
  VERIFICATION_UPLOAD_NOT_POSSIBLE_24H: {
    code: 158,
    type: e.BadRequest,
    en: "Re-recording of a verification vieo is only possible once within 24 hours",
    de: "Das Neuaufnehmen von Verifikationsvideos ist nur einmal pro 24h möglich",
    es: "La regrabación de los vídeos de verificación sólo es posible una vez cada 24 horas",
    fr: "Le réenregistrement des vidéos de vérification n'est possible qu'une fois par 24 heures.",
    it: "La ri-registrazione dei video di verifica è possibile solo una volta ogni 24 ore",
  },
  YOU_DONT_HAVE_ENOUGH_PP_TO_INVITE_USERS: {
    code: 159,
    type: e.BadRequest,
    en: "You do not have enough party points to invite these users",
    de: "Du hast nicht genügend Party-Points um die ausgewählten Nutzer einzuladen",
    es: "No tienes suficientes puntos de fiesta para invitar a los usuarios seleccionados.",
    fr: "Vous n'avez pas assez de Party Points pour inviter les utilisateurs sélectionnés.",
    it: "Non hai abbastanza Party Points per invitare gli utenti selezionati.",
  },
  PARTYGUEST_NOT_FOUND: {
    code: 160,
    type: e.NotFound,
    en: "Partyguest not found",
    de: "Dieser Gast wurde nicht gefunden",
    es: "Este huésped no fue encontrado",
    fr: "Cet invité n'a pas été trouvé",
    it: "Questo ospite non è stato trovato",
  },
  USER_CANNOT_BE_DELETED_FROM_GUESTLIST: {
    code: 161,
    type: e.BadRequest,
    en: "This user cannot be deleted from the guestlist",
    de: "Dieser Nutzer kann nicht von der Gästeliste gelöscht werden",
    es: "Este usuario no puede ser eliminado de la lista de invitados",
    fr: "Cet utilisateur ne peut pas être supprimé de la liste des invités",
    it: "Questo utente non può essere cancellato dalla lista degli ospiti",
  },
  YOU_CANNOT_JOIN_THIS_PARTY: {
    code: 162,
    type: e.BadRequest,
    en: "You cannot join this party",
    de: "Du kannst an dieser Party nicht teilnehmen",
    es: "No puede asistir a esta fiesta",
    fr: "Vous ne pouvez pas assister à cette fête",
    it: "Non puoi partecipare a questa festa",
  },
  CANNOT_RATE_PARTY_WHEN_NOT_ON_SITE: {
    code: 163,
    type: e.BadRequest,
    en: "You cannot rate this party if you were not on site",
    de: "Du kannst diese Party nicht bewerten, da Du nicht anwesend warst",
    es: "No puede calificar esta fiesta porque no estuvo presente",
    fr: "Vous ne pouvez pas noter cette fête car vous n'étiez pas présent.",
    it: "Non puoi valutare questa festa perché non eri presente",
  },
  ALREADY_CHANGED_TO_ARTIST_72H: {
    code: 164,
    type: e.BadRequest,
    en: "You already changed to an artist profile in the last 72 hours",
    de: "Du hast bereits in den letzten 72 Stunden dein Profiltyp auf Artist gestellt",
    es: "Ya has configurado tu tipo de perfil como Artista en las últimas 72 horas.",
    fr: "Vous avez déjà défini votre type de profil en tant qu'artiste au cours des 72 dernières heures.",
    it: "Hai già impostato il tuo tipo di profilo su Artista nelle ultime 72 ore.",
  },
  YOU_CANNOT_BLOCK_YOURSELF: {
    code: 165,
    type: e.BadRequest,
    en: "You cannot block yourself",
    de: "Du kannst dich nicht selbst blockieren",
    es: "No puedes bloquearte",
    fr: "Vous ne pouvez pas vous bloquer",
    it: "Non puoi bloccarti",
  },
  YOU_DONT_HAVE_ENOUGH_PP_TO_BROADCAST_MESSAGE: {
    code: 166,
    type: e.BadRequest,
    en: "You do not have enough party points to broadcast this message",
    de: "Du hast nicht genügend Party-Points um diese Nachricht zu senden",
    es: "No tienes suficientes puntos de partido para enviar este mensaje",
    fr: "Vous n'avez pas assez de points de parti pour envoyer ce message.",
    it: "Non hai abbastanza Punti Partito per inviare questo messaggio",
  },
  RATING_DOES_NOT_EXIST: {
    code: 167,
    type: e.NotFound,
    en: "Rating not found",
    de: "Bewertung existiert nicht",
    es: "La evaluación no existe",
    fr: "L'évaluation n'existe pas",
    it: "La valutazione non esiste",
  },
  COMMENT_DOES_NOT_EXIST: {
    code: 168,
    type: e.NotFound,
    en: "Comment not found",
    de: "Kommentar existiert nicht",
    es: "El comentario no existe",
    fr: "Le commentaire n'existe pas",
    it: "Il commento non esiste",
  },
  RATING_ALREADY_REPORTED: {
    code: 169,
    type: e.BadRequest,
    en: "You already reported this rating",
    de: "Du hast diese Bewertung bereits gemeldet",
    es: "Ya ha informado de esta calificación",
    fr: "Vous avez déjà signalé cette évaluation",
    it: "Hai già segnalato questa valutazione",
  },
  COMMENT_ALREADY_REPORTED: {
    code: 170,
    type: e.BadRequest,
    en: "You already reported this comment",
    de: "Du hast diesen Kommentar bereits gemeldet",
    es: "Ya ha denunciado este comentario",
    fr: "Vous avez déjà signalé ce commentaire",
    it: "Hai già segnalato questo commento",
  },
  NOT_ENOUGH_RIGHTS: {
    code: 171,
    type: e.Forbidden,
    en: "You du not have enough rights for this action",
    de: "Du hast nicht die benötigten Rechte für diese Aktion",
    es: "Usted no tiene los derechos necesarios para esta acción",
    fr: "Vous ne disposez pas des droits nécessaires pour cette action",
    it: "Non hai i diritti necessari per questa azione",
  },
  THIS_USER_IS_NOT_AN_ADMIN: {
    code: 172,
    type: e.BadRequest,
    en: "This user is not an admin",
    de: "Dieser Nutzer ist kein Administratior",
    es: "Este usuario no es un administrador",
    fr: "Cet utilisateur n'est pas un administrateur",
    it: "Questo utente non è un amministratore",
  },
  RESTRICTED_ACTION: {
    code: 173,
    type: e.Forbidden,
    en: "You are not allowed to use this feature",
    de: "Du bist nicht berechtigt dazu diese Aktion auszuführen",
    es: "No está autorizado a realizar esta acción",
    fr: "Vous n'êtes pas autorisé à effectuer cette action",
    it: "Non sei autorizzato ad eseguire questa azione",
  },
  RATE_LIMITED: {
    code: 174,
    type: e.TooManyRequests,
    en: "Too many requests",
    de: "Zu viele Anfragen",
    es: "Demasiadas solicitudes",
    fr: "Trop de demandes",
    it: "Troppe richieste",
  },
  CANNOT_CHANGE_PHONENUMBER: {
    code: 175,
    type: e.BadRequest,
    en: "You cannot change your phone number",
    de: "Du kannst deine Telefonnummer nicht ändern",
    es: "No puede cambiar su número de teléfono",
    fr: "Vous ne pouvez pas changer votre numéro de téléphone",
    it: "Non puoi cambiare il tuo numero di telefono",
  },
  COMPETITION_DOES_NOT_EXIST: {
    code: 176,
    type: e.NotFound,
    en: "Competition not found",
    de: "Wettbewerb existiert nicht",
    es: "La competencia no existe",
    fr: "La concurrence n'existe pas",
    it: "La concorrenza non esiste",
  },
  YOU_ARE_NOT_THE_OWNER_OF_THIS_COMPETITION: {
    code: 177,
    type: e.Forbidden,
    en: "You are not the owner of this competition",
    de: "Du bist nicht der Ersteller dieses Wettbewerbes",
    es: "Usted no es el creador de este concurso",
    fr: "Vous n'êtes pas le créateur de ce concours",
    it: "Non sei il creatore di questo concorso",
  },
  PARTY_NOT_IN_COMPETITION_DATE_RANGE: {
    code: 178,
    type: e.BadRequest,
    en: "This party cannot participate in this competition",
    de: "Diese Party kann nicht an diesem Wettbewerb teilnehmen",
    es: "Esta parte no puede participar en este concurso",
    fr: "Cette partie ne peut pas participer à ce concours",
    it: "Questa parte non può partecipare a questo concorso",
  },
  PARTY_DOES_NOT_BELONG_TO_THIS_COMPETITION: {
    code: 179,
    type: e.BadRequest,
    en: "This party is not part of this competition",
    de: "Diese Party ist nicht Teil dieses Wettbewerbes",
    es: "Esta fiesta no forma parte de este concurso",
    fr: "Cette fête ne fait pas partie de ce concours",
    it: "Questa festa non fa parte di questo concorso",
  },
  SECRET_PARTIES_CANNOT_JOIN_COMPETITIONS: {
    code: 180,
    type: e.BadRequest,
    en: "Secret parties can not participate in competitions",
    de: "Geheime Parties können nicht an Wettbewerben teilnehmen",
    es: "Los partidos secretos no pueden participar en los concursos",
    fr: "Les fêtes secrètes ne peuvent pas participer aux concours",
    it: "I partiti segreti non possono partecipare ai concorsi",
  },
  SECRET_PARTY_PRIVACY_LEVEL_CANNOT_BE_CHANGED: {
    code: 181,
    type: e.BadRequest,
    de: "Geheime Parties können nicht mehr zu offenen oder geschlossenen Parties geändert werden",
    fr: "Les soirées secrètes ne peuvent plus être modifiées en soirées ouvertes ou fermées.",
    it: "Le feste segrete non possono più essere cambiate in feste aperte o chiuse",
    es: "Las fiestas secretas ya no pueden cambiarse por fiestas abiertas o cerradas",
    en: "Secret parties can no longer be changed to open or closed parties",
  },
  USER_MUST_BE_PARTYKING_TO_CHANGE_BANNER: {
    code: 182,
    type: e.BadRequest,
    de: "Dieser Nutzer muss eine Party-King Mitgliedschaft besitzen um ein Profilbanner zu erstellen.",
    fr: "Cet utilisateur doit être membre de Party-King pour pouvoir créer une bannière de profil.",
    it: "Questo utente deve essere iscritto a Party King per creare un banner di profilo.",
    es: "Este usuario debe ser miembro de Party King para crear un banner de perfil.",
    en: "This user must have a Party King membership to create a profile banner.",
  },
  TICKET_ALREADY_SCANNED: {
    code: 183,
    type: e.BadRequest,
    de: "Ticket wurde bereits gescannt.",
    fr: "Le ticket a déjà été scanné.",
    it: "Il biglietto è già stato scansionato.",
    es: "El billete ya ha sido escaneado.",
    en: "Ticket has already been scanned.",
  },
  MENUCARD_ORDER_ALREADY_PROCESSED: {
    code: 184,
    type: e.BadRequest,
    de: "Die Bestellung wurde bereits bearbeitet.",
    fr: "La commande a déjà été traitée.",
    it: "L'ordine è già stato elaborato.",
    es: "El pedido ya se ha tramitado.",
    en: "The order has already been processed.",
  },
  MENUCARD_ORDER_FAILED_NOT_ENOUGH_PP: {
    code: 185,
    type: e.BadRequest,
    de: "Die Bestellung konnte nicht bearbeitet werden, da nicht genügend Party-Punkte vorhanden sind.",
    fr: "La commande n'a pas pu être traitée, car il n'y a pas assez de points de fête.",
    it: "Non è stato possibile elaborare l'ordine perché non ci sono abbastanza punti partito.",
    es: "El pedido no se ha podido procesar porque no hay suficientes puntos de partido.",
    en: "The order could not be processed because there are not enough party points.",
  },
  MENUCARD_ORDER_FAILED_CARD_DECLINED: {
    code: 186,
    type: e.BadRequest,
    de: "Die Bestellung konnte nicht bearbeitet werden, da die Kreditkarte abgelehnt wurde.",
    fr: "La commande n'a pas pu être traitée car la carte de crédit a été refusée.",
    it: "Non è stato possibile elaborare l'ordine perché la carta di credito è stata rifiutata.",
    es: "No se ha podido tramitar el pedido porque la tarjeta de crédito ha sido rechazada.",
    en: "The order could not be processed because the credit card was declined.",
  },
  MENUCARD_ORDER_FAILED_NO_CARD: {
    code: 187,
    type: e.BadRequest,
    de: "Die Bestellung konnte nicht bearbeitet werden, da keine Kreditkarte hinterlegt ist.",
    fr: "La commande n'a pas pu être traitée car aucune carte de crédit n'a été enregistrée.",
    it: "Non è stato possibile elaborare l'ordine perché non c'è nessuna carta di credito in archivio.",
    es: "No se ha podido procesar el pedido porque no hay ninguna tarjeta de crédito registrada.",
    en: "The order could not be processed because there is no credit card on file.",
  },
  CANNOT_ATTACH_MENUCARD_TO_PARTY_IF_PARTY_HAS_NO_TICKETINGSHOP: {
    code: 188,
    type: e.BadRequest,
    de: "Es kann keine Menükarte zu einer Party hinzugefügt werden, wenn die Party keinen Ticketshop hat.",
    fr: "Il n'est pas possible d'ajouter un menu à une fête si celle-ci ne dispose pas d'une billetterie.",
    it: "Non è possibile aggiungere una carta menu a una festa se questa non dispone di una biglietteria.",
    es: "No se podrá añadir ninguna tarjeta de menú a una fiesta si ésta no dispone de tienda de entradas.",
    en: "No menu card can be added to a party if the party does not have a ticket store.",
  },
  MENUCARD_ORDER_FAILED_PP_ORDER_LIMIT_PER_PARTY_REACHED: {
    code: 189,
    type: e.BadRequest,
    de: "Die Bestellung konnte nicht bearbeitet werden, da die maximale Anzahl an Bestellungen mit Party-Punkten pro Party erreicht wurde.",
    fr: "La commande n'a pas pu être traitée car le nombre maximal de commandes avec des points de fête par fête a été atteint.",
    it: "Non è stato possibile elaborare l'ordine perché è stato raggiunto il numero massimo di ordini con punti partito per festa.",
    es: "No se ha podido tramitar el pedido porque se ha alcanzado el número máximo de pedidos con puntos de partido por fiesta.",
    en: "The order could not be processed because the maximum number of orders with party points per party has been reached.",
  },
  TICKETING_TICKET_WAS_REFUNDED: {
    code: 190,
    type: e.BadRequest,
    de: "Ticket wurde erstattet.",
    fr: "Le billet a été remboursé.",
    it: "Il biglietto è stato rimborsato.",
    es: "Se reembolsó el billete.",
    en: "Ticket was refunded.",
  },
  CANNOT_BUY_TICKET_PARTY_IS_CANCELLED: {
    code: 191,
    type: e.BadRequest,
    de: "Ticket kann nicht gekauft werden, da die Party abgesagt wurde.",
    fr: "Le billet ne peut pas être acheté car la fête a été annulée.",
    it: "Il biglietto non può essere acquistato perché la festa è stata annullata.",
    es: "No se puede comprar el billete porque la fiesta ha sido cancelada.",
    en: "Ticket cannot be purchased because the party has been canceled.",
  },
  FORBIDDEN_PARAMETERS: {
    code: 192,
    type: e.BadRequest,
    en: "Forbidden parameters",
    de: "Ungültige Parameter",
    fr: "Paramètres interdits",
    it: "Parametri non consentiti",
    es: "Parámetros prohibidos",
  },
  USER_DISABLED_ADMIN_LOGIN_IN_SETTINGS: {
    code: 193,
    type: e.Forbidden,
    en: "Admin Login is disabled in user settings",
    de: "Admin Login ist in den Einstellungen des Nutzers deaktiviert",
    fr: "La connexion administrateur est désactivée dans les paramètres de l'utilisateur",
    it: "L'accesso amministratore è disabilitato nelle impostazioni dell'utente",
    es: "El inicio de sesión de administrador está deshabilitado en la configuración del usuario",
  },
  ONLY_VERIFIED_USERS_CAN_REQUEST_A_PAYOUT: {
    code: 194,
    type: e.BadRequest,
    en: "Only verified users can request a payout",
    de: "Nur verifizierte Nutzer können eine Auszahlung beantragen",
    fr: "Seuls les utilisateurs vérifiés peuvent demander un paiement",
    it: "Solo gli utenti verificati possono richiedere un pagamento",
    es: "Solo los usuarios verificados pueden solicitar un pago",
  },
};
exports.PAPEO_ERRORS = PAPEO_ERRORS;
exports.papeoError = (error, data) => {
  return new error.type(error.en, { code: error.code, ...data });
};

/**
 * format errors for errors api endpoint
 * example format:
{
  101: {
    en: 'Number not valid',
    xde: 'Telefonnummer ist nicht gültig',
    
  }
}
 */
exports.getErrorsForApiEndpoint = () => {
  const errorsResponse = {};
  Object.entries(PAPEO_ERRORS).map(([key, value]) => {
    errorsResponse[value.code] = { ...value, code: undefined, type: undefined };
  });
  return errorsResponse;
};

// checking for duplicate error codes on startup
(() => {
  const codes = Object.entries(PAPEO_ERRORS).map(([key, error]) => error.code);
  const countReduce = (codes) => {
    return codes.reduce((a, b) => ({ ...a, [b]: (a[b] || 0) + 1 }), {});
  };
  const duplicates = (code) => Object.keys(code).filter((a) => code[a] > 1);
  const duplicatedCodes = duplicates(countReduce(codes));
  if (duplicatedCodes.length > 0) {
    throw new Error(
      `There are duplicate values for error codes: ${duplicatedCodes}`
    );
  }
})();
